---
- hosts: all
  become: yes
  become_method: sudo
  task:
    - name: Clean up Docker images
      community.docker.docker_prune:
        images: yes
        images_filters:
          dangling: false
