---
- hosts: all
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes # apt-get update
        upgrade: full
    - name: "Update dist"
      apt:
         upgrade: dist
    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
