---
- hosts: all
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes # apt-get update
        upgrade: full
    - name: "Update dist"
      apt:
         upgrade: dist
